version: "3.7"

volumes:
    sqlsystem:
    sqldata:
    sqllog:
    sqlbackup:

services:
    sql-server-db:
        container_name: sql-server-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: 7D736b01821884D9C80D
            ACCEPT_EULA: "Y"
        volumes:
            - sqlsystem:/var/opt/mssql/
            - sqldata:/var/opt/sqlserver/data
            - sqllog:/var/opt/sqlserver/log
            - sqlbackup:/var/opt/sqlserver/backup
            - ./mssql_init.sql:/docker-entrypoint-initdb.d/mssql_init.sql
        restart: unless-stopped

